"""add unique constraint on name fields

Revision ID: 7f81b4a0808b
Revises: dc38b26d82e5
Create Date: 2026-06-24 10:15:49.078317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f81b4a0808b'
down_revision: Union[str, None] = 'dc38b26d82e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cocktails', ['name'])
    op.create_unique_constraint(None, 'ingredients', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='unique')
    op.drop_constraint(None, 'cocktails', type_='unique')
    # ### end Alembic commands ###
