"""migrate to MenuItem-centric ERD

Revision ID: a19ebb5afb91
Revises: 9e6cd07af2b4
Create Date: 2026-06-24 11:25:44.849749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a19ebb5afb91'
down_revision: Union[str, None] = '9e6cd07af2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_tags',
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'tag_id')
    )
    op.drop_table('item_tags')
    op.drop_column('items', 'image_url')
    op.drop_column('items', 'description')
    op.add_column('menu_items', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('menu_items', sa.Column('short_description', sa.String(length=300), nullable=True))
    op.add_column('menu_items', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('menu_items', sa.Column('full_description', sa.Text(), nullable=True))
    op.drop_column('menu_items', 'name')
    op.drop_column('menu_items', 'description')
    op.add_column('tags', sa.Column('display_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'display_name')
    op.add_column('menu_items', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('menu_items', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('menu_items', 'full_description')
    op.drop_column('menu_items', 'image_url')
    op.drop_column('menu_items', 'short_description')
    op.drop_column('menu_items', 'display_name')
    op.add_column('items', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_table('item_tags',
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('item_tags_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('item_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id', name=op.f('item_tags_pkey'))
    )
    op.drop_table('menu_item_tags')
    # ### end Alembic commands ###
