"""initial schema

Revision ID: dc38b26d82e5
Revises: 
Create Date: 2026-06-24 10:02:01.506718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc38b26d82e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('alcohol_level', sa.Enum('low', 'medium', 'high', name='alcohollevel'), nullable=False),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('base_spirit', sa.String(length=50), nullable=True),
    sa.Column('glass_type', sa.Enum('highball', 'coupe', 'rocks', 'martini', 'shot', 'wine', 'etc', name='glasstype'), nullable=False),
    sa.Column('method', sa.Enum('build', 'shake', 'stir', 'blend', name='cocktailmethod'), nullable=False),
    sa.Column('sweetness', sa.Integer(), nullable=False),
    sa.Column('sourness', sa.Integer(), nullable=False),
    sa.Column('bitterness', sa.Integer(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=False),
    sa.Column('freshness', sa.Integer(), nullable=False),
    sa.Column('garnish', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('base_spirit', 'liqueur', 'juice', 'soda', 'syrup', 'fruit', 'garnish', 'bitter', 'dairy', 'etc', name='ingredientcategory'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.Enum('cocktail', 'whisky', name='ordertype'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('requested', 'preparing', 'served', 'canceled', name='orderstatus'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktail_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cocktail_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktail_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cocktail_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cocktail_steps')
    op.drop_table('cocktail_ingredients')
    op.drop_table('orders')
    op.drop_table('ingredients')
    op.drop_table('cocktails')
    # ### end Alembic commands ###
